### ISSUE TITLE
"Location Information" table is blank

### ISSUE THREAD

**Issue by mattsahn** [grassrootsgrocery/admin-portal#123]
When you bring up the Delivery and Location Information page for an event, the "Location Information" table at the bottom is currently blank for every event. The "Driver Information" table is populated fine.

https://portal.grassrootsgrocery.org/events/driver-location-info/recQQI30v9mP5Ffck

Per the below screenshot, when I look at the /dropoff-locations/ API call the frontend makes, it has results in the response. So, it's not a matter of not getting data back. Also, the "Add Dropoff Location" popup has data/rows, as well. So, not sure why the main table is blank.

![image](https://github.com/grassrootsgrocery/admin-portal/assets/15386131/54a444e0-6641-4eb0-ad3c-9b94e1a3d3fd)

**Comment by jasoncavanaugh** [comment]
@mattsahn  @bdey05  This is by design. It's not a great UX, so I would suggest turning this ticket into finding a way to improve this. But the idea is that a location is not considered to be part of the event until it has non-empty start and stop times. If you open the dropoff location organizer, if you add a start and stop time to the location, you will see that it shows up in the table.

**Comment by mattsahn** [comment]
@jasoncavanaugh, thanks, that makes sense. I was thrown because when I looked on Saturday (8/12), it was blank, despite there being an active event that had happened earlier in the day with locations that had assigned deliveries while the rest of the app was populated with drivers, for example. 

As far as being empty before any deliveries have start/stop dates, yes, we should come up with a better UX. Maybe a message like "No scheduled deliveries for this event yet". But, should also consider adding locations for which there are assigned deliveries even if start/stop is missing.

I'll update this ticket or close and start a new one for that work.

**Comment by mattsahn** [comment]
Created new issue #130 for this. Closing this ticket.
