### ISSUE TITLE
Server logging should include timestamps

### ISSUE THREAD

**Issue by mattsahn** [grassrootsgrocery/admin-portal#45]
I was looking into an issue that Dan reported of not being able to trigger Make automations so I was looking at the log in Railway to see evidence of that, when it happened, etc. But, there are no timestamps in the logs currently.

![image](https://user-images.githubusercontent.com/15386131/218287361-187f2d9c-207d-48d9-a020-7ea71ebc75c8.png)

I see it's using raw console.log() statements which we should upgrade to something better suited for a production app. Below articles have some suggestions on log frameworks to use.

https://blog.appsignal.com/2021/09/01/best-practices-for-logging-in-nodejs.html
https://betterstack.com/community/guides/logging/nodejs-logging-best-practices/

**Comment by zuechai** [comment]
@mattsahn I started working on the logger. Can you take a look at my branch when you have time and let me know if what I've done so far aligns with what you were thinking for this? The file of note is /loggerUtils/logger.ts. The other changes I made are changing `console.log`s to `logger.info`.

**Comment by mattsahn** [comment]
Looks good so far. Winston looks like a good choice in terms of simplicity and popularity.  I thought that the PR would trigger Railway to deploy it automatically as its own URL/deployment so that we could view as part of the PR. Not sure why that didn't work, so i'm going to look at that some more.

**Comment by zuechai** [comment]
Resolved in PR #61
