### ISSUE TITLE
Ask for confirmation password for triggering automations

### ISSUE THREAD

**Issue by mattsahn** [grassrootsgrocery/admin-portal#52]
In the portal, there are some buttons for triggering mass texts via Make automations. These are done by calling specific Make webhooks to trigger Make scenarios.  Since these result in significant actions, like texting tens of people, it's important that they not be triggered frivolously or by accident.  As such, we should implement a technique in the UI for confirming "major" actions before executing them.  There should be at least a pop-up and then, ideally, we have a special password (set as an environment variable), that needs to be entered to proceed and actually trigger the automation. Only Dan and specific event admins would have this password to ensure that only they can trigger major actions.

We should make it easy to associate this kind of validation step for any kind of button/action throughout the site that we deem to be "major". 

![image](https://user-images.githubusercontent.com/15386131/218340150-8fe77839-305d-491f-b486-770f7a3051ee.png)

Tagging @danthefridgeman

**Comment by hgreenhut** [comment]
Updated assignment here https://grassroots-grocery.monday.com/boards/2826542086/views/103721956/pulses/4815300549
