### ISSUE TITLE
Fix incorrect times in "Location Information" table and "Dropoff Location Organizer" popup

### ISSUE THREAD

**Issue by jasoncavanaugh** [grassrootsgrocery/admin-portal#62]
Currently, the times in the location information table and dropoff organizer popup are early by 5 hours (likely some issue with converting from UTC). These should be fixed to display the correct time in EST. 

![image](https://user-images.githubusercontent.com/66095097/220802779-a33f26c1-540f-4d9e-b28e-2c62b8242d29.png)
![image](https://user-images.githubusercontent.com/66095097/220802825-ab15aceb-69b5-4d47-a5b4-bfcb0f3aa488.png)

**Comment by mattsahn** [comment]
Closing this as all the times have been fixed.
