### ISSUE TITLE
Some event page summary stats are incorrect

### ISSUE THREAD

**Issue by mattsahn** [grassrootsgrocery/admin-portal#64]
Looking at the summary stats for event pages, there are some incorrect numbers being displayed:

- "Both Drivers & Packers" - For 3/4, showing 4 when there are actually 22.
- "Only Packers" - showing 5 when there are actually 17
- "# of special groups" - shows 5, but there are actually only 4. I think this is because it's counting "N/A" as 1, which it shouldn't.

So, the logic for these counts needs to be checked and updated to correctly reflect counts.

![image](https://user-images.githubusercontent.com/15386131/221419224-8e0f98e2-e1c6-45b7-9457-46fd23bb070a.png)

**Comment by alexkulkarni** [comment]
So I've been poking around and I'm pretty sure this is a special events issue. If there are no special events, the test cases work fine. In events.ts, something weird is happening with the processgeneralevents numbers getting communicated to other parts of the code. Only started looking at this code this week, so someone else may know how those values are passed from one part of the code to another better.

**Comment by mattsahn** [comment]
@alexkulkarni, any more luck?  Probably there is some wrong logic happening in the airtable formulas and/or in the app code and may be tied to presence of special groups. Are you able to reproduce with the test DB? Not sure if that one has this case or not.

**Comment by alexkulkarni** [comment]
is the test db on AIrtable? currently i can't make any edits on AIrtable and I don't know how to see the formulas to check

**Comment by mattsahn** [comment]
Let me see if I can find a reproducible example in the test DB.  The edit and full view access to Airtable requires a paid account for you, which we can do if needed, but I think this particular one just needs a definite example in the test DB that shows up in the frontend and that should be enough to determine where the bug is.

**Comment by mattsahn** [comment]
@alexkulkarni, look at event for 2/11/2023 in the test DB (http://localhost:5173/events/recjBht3fOMKJe5z3)

![image](https://github.com/grassrootsgrocery/admin-portal/assets/15386131/b81cf79a-3da4-4aad-a4c4-1f2c23210927)

The 2 metrics are wrong, which you can validate by playing with the filters in the volunteer table and can see what the real numbers should be.

You can look in client/src/pages/Events/Events.tsx and server/routes/events.ts for related code that powers that.

**Comment by mattsahn** [comment]
I see an issue with the driver count with the new version. When I run your branch, Feb 11 shows 5 drivers, instead of 6. The 5 seems to be based on "confirmed" drivers, but we want to show both confirmed and unconfirmed. We should exclude "Can't Come" drivers, so the number should be 6 i'm pretty sure.

![image](https://github.com/grassrootsgrocery/admin-portal/assets/15386131/be17fde0-d7c6-47c9-8f70-d0746f192345)

Tagging @hgreenhut, too. Henry, you had asked about special groups count. For Feb 11, I see "St. Augustine's" and "Greenacres". The rest are "N/A". So, this count should be "2", not "3". It must be considering "N/A" as the 3rd special group to get that count?
![image](https://github.com/grassrootsgrocery/admin-portal/assets/15386131/6aa50927-d5b9-49f6-b41c-bc08859f58df)

**Comment by mattsahn** [comment]
Resolved in #102
