### ISSUE TITLE
Update Verbiage on Event Details [Upcoming Events Page]

### ISSUE THREAD

**Issue by ifiorita** [grassrootsgrocery/admin-portal#81]
The purpose of this enhancement is to ensure that the verbiage used on the event details page is intuitive and not duplicative - and reflects accurate information 

**Verbiage and Logic:** 

UI Label: "Drivers Only"
Logic: should display the number of individuals signed up to drive, only. 

UI Label: "Packers Only"
Logic: should display the number of individuals signed up to pack, only. 

UI Label: "# Driving and Packing" 
Logic: should display the total count of volunteers signed up to distribute (the sum of registered volunteers and guests that have signed up to sort/distribute.) 

**Tasks**
Task#1: Add/Update UI labels, per guidance above. 
Task #2: remove "Total Participants". 

![Update verbiage on event details](https://github.com/grassrootsgrocery/admin-portal/assets/133153703/06b45794-5650-4f80-ba65-aa54a8b4e142)

**Comment by alexkulkarni** [comment]
just wanted to mark that i am working on this now

**Comment by mattsahn** [comment]
Closing this issue as these updates have been made
